### ISSUE TITLE
Software Installation

### ISSUE THREAD

**Issue by vhick** [astolfogit/miwifi-r3-production#6]
Is software installation available for this firmware? Like SQM?

Thank you.

**Comment by kohawk** [comment]
Of course it is, either download .ipk files from OpenWRT repo itself, or use opkg install
The problem is that in distfeeds.conf there is a /x/ repo, which doesn't exist on OpenWRT servers and prevents you from completing opkg update
Try to delete the last string in distfeeds.conf (make a backup before that)
